### ISSUE TITLE
Tracking issue for velvet-core release v0.1.0

### ISSUE THREAD

**Issue by seatonullberg** [seatonullberg/velvet#1]
This issue tracks the progress towards the v0.1.0 release of `velvet-core` on branch [dev](https://github.com/seatonullberg/velvet/tree/dev).

- [x] Specify `PairPotential` interface
- [x] Implement Lennard-Jones pair potential
- [x] Implement Morse pair potential
- [x] Implement Mie pair potential
- [x] Specify `Property` interface
- [x] Implement calculation of atomic forces as a property
- [x] Implement calculation of potential energy as a property
- [x] Specify `Integrator` interface
- [x] Implement the velocity Verlet algorithm as an integrator
- [x] Conduct a simulation of Ar gas in the NVE ensemble
- [x] Add documentation

**Comment by seatonullberg** [comment]
Available on [crates.io](https://crates.io/crates/velvet-core/0.1.0).
