### ISSUE TITLE
Tracking issue for velvet-core release v0.5.0

### ISSUE THREAD

**Issue by seatonullberg** [seatonullberg/velvet#14]
This issue tracks the progress towards the v0.5.0 release of `velvet-core` on the branch [master](https://github.com/seatonullberg/velvet/tree/master).

- [ ] Add support for coulomb potentials
    - [ ] Implement the Wolf summation
- [x]  Enable optional `f64` storage type as a cargo feature
- [x] Use neighbor lists to enhance performance of nonbonded interactions
- [ ] Conduct a simulation of NaCl in the NVT ensemble
    - [ ] Add as an example
    - [ ] Validate against LAMMPS
