### ISSUE TITLE
Tracking issue for velvet-core release v0.2.0

### ISSUE THREAD

**Issue by seatonullberg** [seatonullberg/velvet#4]
This issue tracks the progress towards the v0.2.0 release of `velvet-core` on branch [dev](https://github.com/seatonullberg/velvet/tree/dev).

- [x] Add Boltzmann distribution temperature initialization
- [x] Specify `Thermostat` interface
- [x] Implement calculation of temperature as a property
- [x] Implement Nose-Hoover thermostat
- [x] Implement Berendsen thermostat
- [x] Conduct a simulation of Ar gas in the NVT ensemble
- [x] Add serde support for `System` and `Potentials`
- [x] Add benchmark test suite
- [x] Add documentation

**Comment by seatonullberg** [comment]
Available on [crates.io](https://crates.io/crates/velvet-core/0.2.0)
