### ISSUE TITLE
Tracking issue for velvet-core release v0.3.0

### ISSUE THREAD

**Issue by seatonullberg** [seatonullberg/velvet#8]
This issue tracks the progress towards the v0.3.0 release of `velvet-core` on the branch [dev](https://github.com/seatonullberg/velvet/tree/dev).

- [x] Specify `Propagator` interface
- [x] Implement `MolecularDynamics` as a propagator
- [x] Add support for HDF5 output
- [x] Implement `Configuration`
- [x] Implement high-level `Simulation` abstraction
- [x] Add `Serialize` and `Deserialize` support for `Output`
- [x] Add `Serialize` and `Deserialize` support for `Simulation`
    - [x] Add `Serialize` and `Deserialize` support for `Propagator`
    - [x] Add `Serialize` and `Deserialize` support for `Integrator`
    - [x] Add `Serialize` and `Deserialize` support for `Thermostat`
- [x] Add `prelude` module
- [x] Update documentation
- [x] Update examples

**Comment by seatonullberg** [comment]
Available on [crates.io](https://crates.io/crates/velvet-core/0.3.0).
